const path = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");

const webpack = require("webpack");
const webpackDevServer = require("webpack-dev-server");

const config = {
  mode: "development",
  entry: [
    // Runtime code for hot module replacement
    "webpack/hot/dev-server.js",
    // Dev server client for web socket transport, hot and live reload logic
    "webpack-dev-server/client/index.js?hot=true&live-reload=true",
    // Your entry
    "./src/index.js",
  ],
  devtool: "inline-source-map",
  plugins: [
    // Plugin for hot module replacement
    new webpack.HotModuleReplacementPlugin(),
    new HtmlWebpackPlugin({
      title: "Hot Module Replacement",
    }),
  ],
  module: {
    rules: [
      {
        test: /\.css$/,
        use: ["style-loader", "css-loader"],
      },
    ],
  },
  output: {
    filename: "[name].bundle.js",
    path: path.resolve(__dirname, "dist"),
    clean: true,
  },
};
const compiler = webpack(config); // 1. 解析文件

console.log("compiler", compiler);

// `hot` and `client` options are disabled because we added them manually
const server = new webpackDevServer({ hot: false, client: false }, compiler); // 2. 运行时
// console.log("server", server);

(async () => {
  await server.start();
  console.log("dev server is running");
})();

// 1. compiler

// 2. server
// {
//     compiler: <ref *1> Compiler {
//       hooks: {
//         initialize: [Hook],
//         shouldEmit: [Hook],
//         done: [Hook],
//         afterDone: [Hook],
//         additionalPass: [Hook],
//         beforeRun: [Hook],
//         run: [Hook],
//         emit: [Hook],
//         assetEmitted: [Hook],
//         afterEmit: [Hook],
//         thisCompilation: [Hook],
//         compilation: [Hook],
//         normalModuleFactory: [Hook],
//         contextModuleFactory: [Hook],
//         beforeCompile: [Hook],
//         compile: [Hook],
//         make: [Hook],
//         finishMake: [Hook],
//         afterCompile: [Hook],
//         readRecords: [Hook],
//         emitRecords: [Hook],
//         watchRun: [Hook],
//         failed: [Hook],
//         invalid: [Hook],
//         watchClose: [Hook],
//         shutdown: [Hook],
//         infrastructureLog: [Hook],
//         environment: [Hook],
//         afterEnvironment: [Hook],
//         afterPlugins: [Hook],
//         afterResolvers: [Hook],
//         entryOption: [Hook]
//       },
//       webpack: [Function: f] {
//         webpack: [Getter],
//         validate: [Getter],
//         validateSchema: [Getter],
//         version: [Getter],
//         cli: [Getter],
//         AutomaticPrefetchPlugin: [Getter],
//         AsyncDependenciesBlock: [Getter],
//         BannerPlugin: [Getter],
//         Cache: [Getter],
//         Chunk: [Getter],
//         ChunkGraph: [Getter],
//         CleanPlugin: [Getter],
//         Compilation: [Getter],
//         Compiler: [Getter],
//         ConcatenationScope: [Getter],
//         ContextExclusionPlugin: [Getter],
//         ContextReplacementPlugin: [Getter],
//         DefinePlugin: [Getter],
//         DelegatedPlugin: [Getter],
//         Dependency: [Getter],
//         DllPlugin: [Getter],
//         DllReferencePlugin: [Getter],
//         DynamicEntryPlugin: [Getter],
//         EntryOptionPlugin: [Getter],
//         EntryPlugin: [Getter],
//         EnvironmentPlugin: [Getter],
//         EvalDevToolModulePlugin: [Getter],
//         EvalSourceMapDevToolPlugin: [Getter],
//         ExternalModule: [Getter],
//         ExternalsPlugin: [Getter],
//         Generator: [Getter],
//         HotUpdateChunk: [Getter],
//         HotModuleReplacementPlugin: [Getter],
//         IgnorePlugin: [Getter],
//         JavascriptModulesPlugin: [Getter],
//         LibManifestPlugin: [Getter],
//         LibraryTemplatePlugin: [Getter],
//         LoaderOptionsPlugin: [Getter],
//         LoaderTargetPlugin: [Getter],
//         Module: [Getter],
//         ModuleFilenameHelpers: [Getter],
//         ModuleGraph: [Getter],
//         ModuleGraphConnection: [Getter],
//         NoEmitOnErrorsPlugin: [Getter],
//         NormalModule: [Getter],
//         NormalModuleReplacementPlugin: [Getter],
//         MultiCompiler: [Getter],
//         Parser: [Getter],
//         PrefetchPlugin: [Getter],
//         ProgressPlugin: [Getter],
//         ProvidePlugin: [Getter],
//         RuntimeGlobals: [Getter],
//         RuntimeModule: [Getter],
//         SingleEntryPlugin: [Getter],
//         SourceMapDevToolPlugin: [Getter],
//         Stats: [Getter],
//         Template: [Getter],
//         UsageState: [Getter],
//         WatchIgnorePlugin: [Getter],
//         WebpackError: [Getter],
//         WebpackOptionsApply: [Getter],
//         WebpackOptionsDefaulter: [Getter],
//         WebpackOptionsValidationError: [Getter],
//         ValidationError: [Getter],
//         cache: [Object],
//         config: [Object],
//         dependencies: [Object],
//         ids: [Object],
//         javascript: [Object],
//         optimize: [Object],
//         runtime: [Object],
//         prefetch: [Object],
//         web: [Object],
//         webworker: [Object],
//         node: [Object],
//         electron: [Object],
//         wasm: [Object],
//         library: [Object],
//         container: [Object],
//         sharing: [Object],
//         debug: [Object],
//         util: [Object],
//         sources: [Getter],
//         experiments: [Object]
//       },
//       name: undefined,
//       parentCompilation: undefined,
//       root: [Circular *1],
//       outputPath: '/Users/ryanzhou/Desktop/webpack5-guide/11. 模块热替换/dist',
//       watching: undefined,
//       outputFileSystem: {
//         appendFile: [Function: appendFile],
//         appendFileSync: [Function: appendFileSync],
//         access: [Function: access],
//         accessSync: [Function: accessSync],
//         chown: [Function (anonymous)],
//         chownSync: [Function (anonymous)],
//         chmod: [Function (anonymous)],
//         chmodSync: [Function (anonymous)],
//         close: [Function: close],
//         closeSync: [Function: closeSync],
//         copyFile: [Function: copyFile],
//         copyFileSync: [Function: copyFileSync],
//         cp: [Function: cp],
//         cpSync: [Function: cpSync],
//         createReadStream: [Function: createReadStream],
//         createWriteStream: [Function: createWriteStream],
//         exists: [Function: exists],
//         existsSync: [Function: existsSync],
//         fchown: [Function (anonymous)],
//         fchownSync: [Function (anonymous)],
//         fchmod: [Function (anonymous)],
//         fchmodSync: [Function (anonymous)],
//         fdatasync: [Function: fdatasync],
//         fdatasyncSync: [Function: fdatasyncSync],
//         fstat: [Function (anonymous)],
//         fstatSync: [Function (anonymous)],
//         fsync: [Function: fsync],
//         fsyncSync: [Function: fsyncSync],
//         ftruncate: [Function: ftruncate],
//         ftruncateSync: [Function: ftruncateSync],
//         futimes: [Function: futimes],
//         futimesSync: [Function: futimesSync],
//         lchown: [Function (anonymous)],
//         lchownSync: [Function (anonymous)],
//         lchmod: [Function (anonymous)],
//         lchmodSync: [Function (anonymous)],
//         link: [Function: link],
//         linkSync: [Function: linkSync],
//         lstat: [Function (anonymous)],
//         lstatSync: [Function (anonymous)],
//         lutimes: [Function: lutimes],
//         lutimesSync: [Function: lutimesSync],
//         mkdir: [Function: mkdir],
//         mkdirSync: [Function: mkdirSync],
//         mkdtemp: [Function: mkdtemp],
//         mkdtempSync: [Function: mkdtempSync],
//         open: [Function: open],
//         openSync: [Function: openSync],
//         opendir: [Function: opendir],
//         opendirSync: [Function: opendirSync],
//         readdir: [Function: readdir],
//         readdirSync: [Function: readdirSync],
//         read: [Function: read],
//         readSync: [Function (anonymous)],
//         readv: [Function: readv],
//         readvSync: [Function: readvSync],
//         readFile: [Function: readFile],
//         readFileSync: [Function: readFileSync],
//         readlink: [Function: readlink],
//         readlinkSync: [Function: readlinkSync],
//         realpath: [Function],
//         realpathSync: [Function],
//         rename: [Function: rename],
//         renameSync: [Function: renameSync],
//         rm: [Function: rm],
//         rmSync: [Function: rmSync],
//         rmdir: [Function: rmdir],
//         rmdirSync: [Function: rmdirSync],
//         stat: [Function (anonymous)],
//         statSync: [Function (anonymous)],
//         symlink: [Function: symlink],
//         symlinkSync: [Function: symlinkSync],
//         truncate: [Function: truncate],
//         truncateSync: [Function: truncateSync],
//         unwatchFile: [Function: unwatchFile],
//         unlink: [Function: unlink],
//         unlinkSync: [Function: unlinkSync],
//         utimes: [Function: utimes],
//         utimesSync: [Function: utimesSync],
//         watch: [Function: watch],
//         watchFile: [Function: watchFile],
//         writeFile: [Function: writeFile],
//         writeFileSync: [Function: writeFileSync],
//         write: [Function: write],
//         writeSync: [Function: writeSync],
//         writev: [Function: writev],
//         writevSync: [Function: writevSync],
//         Dir: [class Dir],
//         Dirent: [class Dirent],
//         Stats: [Function: Stats],
//         ReadStream: [Getter/Setter],
//         WriteStream: [Getter/Setter],
//         FileReadStream: [Getter/Setter],
//         FileWriteStream: [Getter/Setter],
//         _toUnixTimestamp: [Function: toUnixTimestamp],
//         F_OK: 0,
//         R_OK: 4,
//         W_OK: 2,
//         X_OK: 1,
//         constants: [Object: null prototype],
//         promises: [Getter],
//         gracefulify: [Function: patch]
//       },
//       intermediateFileSystem: {
//         appendFile: [Function: appendFile],
//         appendFileSync: [Function: appendFileSync],
//         access: [Function: access],
//         accessSync: [Function: accessSync],
//         chown: [Function (anonymous)],
//         chownSync: [Function (anonymous)],
//         chmod: [Function (anonymous)],
//         chmodSync: [Function (anonymous)],
//         close: [Function: close],
//         closeSync: [Function: closeSync],
//         copyFile: [Function: copyFile],
//         copyFileSync: [Function: copyFileSync],
//         cp: [Function: cp],
//         cpSync: [Function: cpSync],
//         createReadStream: [Function: createReadStream],
//         createWriteStream: [Function: createWriteStream],
//         exists: [Function: exists],
//         existsSync: [Function: existsSync],
//         fchown: [Function (anonymous)],
//         fchownSync: [Function (anonymous)],
//         fchmod: [Function (anonymous)],
//         fchmodSync: [Function (anonymous)],
//         fdatasync: [Function: fdatasync],
//         fdatasyncSync: [Function: fdatasyncSync],
//         fstat: [Function (anonymous)],
//         fstatSync: [Function (anonymous)],
//         fsync: [Function: fsync],
//         fsyncSync: [Function: fsyncSync],
//         ftruncate: [Function: ftruncate],
//         ftruncateSync: [Function: ftruncateSync],
//         futimes: [Function: futimes],
//         futimesSync: [Function: futimesSync],
//         lchown: [Function (anonymous)],
//         lchownSync: [Function (anonymous)],
//         lchmod: [Function (anonymous)],
//         lchmodSync: [Function (anonymous)],
//         link: [Function: link],
//         linkSync: [Function: linkSync],
//         lstat: [Function (anonymous)],
//         lstatSync: [Function (anonymous)],
//         lutimes: [Function: lutimes],
//         lutimesSync: [Function: lutimesSync],
//         mkdir: [Function: mkdir],
//         mkdirSync: [Function: mkdirSync],
//         mkdtemp: [Function: mkdtemp],
//         mkdtempSync: [Function: mkdtempSync],
//         open: [Function: open],
//         openSync: [Function: openSync],
//         opendir: [Function: opendir],
//         opendirSync: [Function: opendirSync],
//         readdir: [Function: readdir],
//         readdirSync: [Function: readdirSync],
//         read: [Function: read],
//         readSync: [Function (anonymous)],
//         readv: [Function: readv],
//         readvSync: [Function: readvSync],
//         readFile: [Function: readFile],
//         readFileSync: [Function: readFileSync],
//         readlink: [Function: readlink],
//         readlinkSync: [Function: readlinkSync],
//         realpath: [Function],
//         realpathSync: [Function],
//         rename: [Function: rename],
//         renameSync: [Function: renameSync],
//         rm: [Function: rm],
//         rmSync: [Function: rmSync],
//         rmdir: [Function: rmdir],
//         rmdirSync: [Function: rmdirSync],
//         stat: [Function (anonymous)],
//         statSync: [Function (anonymous)],
//         symlink: [Function: symlink],
//         symlinkSync: [Function: symlinkSync],
//         truncate: [Function: truncate],
//         truncateSync: [Function: truncateSync],
//         unwatchFile: [Function: unwatchFile],
//         unlink: [Function: unlink],
//         unlinkSync: [Function: unlinkSync],
//         utimes: [Function: utimes],
//         utimesSync: [Function: utimesSync],
//         watch: [Function: watch],
//         watchFile: [Function: watchFile],
//         writeFile: [Function: writeFile],
//         writeFileSync: [Function: writeFileSync],
//         write: [Function: write],
//         writeSync: [Function: writeSync],
//         writev: [Function: writev],
//         writevSync: [Function: writevSync],
//         Dir: [class Dir],
//         Dirent: [class Dirent],
//         Stats: [Function: Stats],
//         ReadStream: [Getter/Setter],
//         WriteStream: [Getter/Setter],
//         FileReadStream: [Getter/Setter],
//         FileWriteStream: [Getter/Setter],
//         _toUnixTimestamp: [Function: toUnixTimestamp],
//         F_OK: 0,
//         R_OK: 4,
//         W_OK: 2,
//         X_OK: 1,
//         constants: [Object: null prototype],
//         promises: [Getter],
//         gracefulify: [Function: patch]
//       },
//       inputFileSystem: CachedInputFileSystem {
//         fileSystem: [Object],
//         _lstatBackend: [CacheBackend],
//         lstat: [Function: bound provide],
//         lstatSync: [Function: bound provideSync],
//         _statBackend: [CacheBackend],
//         stat: [Function: bound provide],
//         statSync: [Function: bound provideSync],
//         _readdirBackend: [CacheBackend],
//         readdir: [Function: bound provide],
//         readdirSync: [Function: bound provideSync],
//         _readFileBackend: [CacheBackend],
//         readFile: [Function: bound provide],
//         readFileSync: [Function: bound provideSync],
//         _readJsonBackend: [CacheBackend],
//         readJson: [Function: bound provide],
//         readJsonSync: [Function: bound provideSync],
//         _readlinkBackend: [CacheBackend],
//         readlink: [Function: bound provide],
//         readlinkSync: [Function: bound provideSync]
//       },
//       watchFileSystem: NodeWatchFileSystem {
//         inputFileSystem: [CachedInputFileSystem],
//         watcherOptions: [Object],
//         watcher: [Watchpack]
//       },
//       recordsInputPath: null,
//       recordsOutputPath: null,
//       records: {},
//       managedPaths: Set(1) {
//         '/Users/ryanzhou/Desktop/webpack5-guide/11. 模块热替换/node_modules/'
//       },
//       immutablePaths: Set(0) {},
//       modifiedFiles: undefined,
//       removedFiles: undefined,
//       fileTimestamps: undefined,
//       contextTimestamps: undefined,
//       fsStartTime: undefined,
//       resolverFactory: ResolverFactory { hooks: [Object], cache: Map(0) {} },
//       infrastructureLogger: [Function: logger],
//       options: {
//         amd: undefined,
//         bail: undefined,
//         cache: [Object],
//         context: '/Users/ryanzhou/Desktop/webpack5-guide/11. 模块热替换',
//         dependencies: undefined,
//         devServer: undefined,
//         devtool: 'inline-source-map',
//         entry: [Object],
//         experiments: [Object],
//         externals: undefined,
//         externalsPresets: [Object],
//         externalsType: 'var',
//         ignoreWarnings: undefined,
//         infrastructureLogging: [Object],
//         loader: [Object],
//         mode: 'development',
//         module: [Object],
//         name: undefined,
//         node: [Object],
//         optimization: [Object],
//         output: [Object],
//         parallelism: 100,
//         performance: false,
//         plugins: [Array],
//         profile: false,
//         recordsInputPath: false,
//         recordsOutputPath: false,
//         resolve: [Object],
//         resolveLoader: [Object],
//         snapshot: [Object],
//         stats: {},
//         target: 'web',
//         watch: false,
//         watchOptions: {}
//       },
//       context: '/Users/ryanzhou/Desktop/webpack5-guide/11. 模块热替换',
//       requestShortener: RequestShortener { contextify: [Function: boundFn] },
//       cache: Cache { hooks: [Object] },
//       moduleMemCaches: undefined,
//       compilerPath: '',
//       running: false,
//       idle: false,
//       watchMode: false,
//       _backCompat: true,
//       _lastCompilation: undefined,
//       _lastNormalModuleFactory: undefined,
//       _assetEmittingSourceCache: WeakMap { <items unknown> },
//       _assetEmittingWrittenFiles: Map(0) {},
//       _assetEmittingPreviousFiles: Set(0) {}
//     },
//     logger: WebpackLogger {
//       getChildLogger: [Function (anonymous)],
//       [Symbol(webpack logger raw log method)]: [Function (anonymous)]
//     },
//     options: { hot: false, client: false },
//     staticWatchers: [],
//     listeners: [],
//     webSocketProxies: [],
//     sockets: [],
//     currentHash: undefined
//   }
